### PR TITLE
adding in log in example using selenium

### PR DESCRIPTION
**Pull request by bantl23**
I think I got the log in to work, please try it out. If I understand the issue correctly, I think the key was waiting for the javascript to load before searching the page. Anyway I hope this is helpful, if not feel free to ignore.

### CODE REVIEW

**Comment by bantl23** [comment]
I think I see the the wall you hit now. You were trying to use PhantomJS to do this headless.

setting: `driver = webdriver.Firefox()` works fine
setting: `driver = webdriver.PhantomJS()` does not work

So maybe the issue is in PhantomJS?

**Comment by bantl23** [comment]
Also I'm using python 3

**Comment by WestbrookT** [comment]
Ya, I think cloudflare recognizes the phantomjs user agent, and blocks it.
So thats why phantom js won't work, unless we can spoof it some other way.

**Comment by bantl23** [comment]
What OS are you using?

**Comment by WestbrookT** [comment]
Windows, my environment is waaaay messed up for programming.

**Comment by WestbrookT** [comment]
I have to go to work, so I'll format everything when I get home. Thank you
for your help though, I hadn't thought to try firefox. It didn't work the
first time, because I had waterfox installed.

**Comment by bantl23** [comment]
No problem. I'll see if I can't get it to work headless...

**Comment by WestbrookT** [comment]
You might try ghost.py, I think I couldn't get it to work because of my
environment, somehow I had an audio issue. Good luck.

**Comment by bantl23** [comment]
I tried ghost.py and couldn't get it to work. I get, what I believe, is the same audio error. Well the error is actually a warning for me. I don't think that warning stops the execution but "header-login" class is not showing up up so I can't "click" to login. The only way I could get it to work is with selenium and firefox. I'm guessing that is a no go as it's not really headless.

**Comment by WestbrookT** [comment]
If its the best we can get, then thats what the API will have.

**Pull request merged**
